//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lppa.Data
{
    using System;
    using System.Collections.Generic;
    using Entities;

    public partial class Cliente
    {
        LppaBD db = new LppaBD();

        public int ID { get; set; }
        public string Nombre { get; set; }
        public string Apellido { get; set; }
        public long DNI { get; set; }
        public string Domicilio { get; set; }
        public string EstadoCivil { get; set; }
        public System.DateTime FechaNacimiento { get; set; }
        public decimal Ingreso { get; set; }
        public string Sexo { get; set; }
        public string Ocupacion { get; set; }
        public int CodEstado { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string ChangedBy { get; set; }
        public System.DateTime ChangedOn { get; set; }

        public void Insert(ClienteEntity cliente)
        {
            cliente.ChangedBy = Guid.NewGuid().ToString();
            cliente.ChangedOn = DateTime.Now;
            cliente.CreatedBy = Guid.NewGuid().ToString();
            cliente.CreatedOn = DateTime.Now;
            cliente.CodEstado = 1;

            db.TablaCliente.Add(cliente);
            //db.Cliente.Add(cliente);
            db.SaveChanges();
        }

       
        public List<ClienteEntity> ListarTodos()
        {
            return null;
        }
    }
}
