//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lppa.Data
{
    using System;
    using System.Collections.Generic;
    using Entities;
    using System.Data.SqlClient;

    public partial class Cliente
    {
       LppaBD db = new LppaBD();

        public int ID { get; set; }
        public string Nombre { get; set; }
        public string Apellido { get; set; }
        public long DNI { get; set; }
        public string Domicilio { get; set; }
        public string EstadoCivil { get; set; }
        public System.DateTime FechaNacimiento { get; set; }
        public decimal Ingreso { get; set; }
        public string Sexo { get; set; }
        public string Ocupacion { get; set; }
        public int CodEstado { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string ChangedBy { get; set; }
        public System.DateTime ChangedOn { get; set; }

        public void Insert(ClienteEntity cliente)
        {
            var nuevoCliente = new Cliente()
            {
                Nombre = cliente.Nombre,
                Apellido = cliente.Apellido,
                DNI = cliente.DNI,
                Domicilio = cliente.Domicilio,
                Ingreso = cliente.Ingreso,
                EstadoCivil = cliente.EstadoCivil,
                FechaNacimiento = cliente.FechaNacimiento,
                Ocupacion = cliente.Ocupacion,
                Sexo = cliente.Sexo,
                ChangedBy = Guid.NewGuid().ToString(),
                ChangedOn = DateTime.Now,
                CreatedBy = Guid.NewGuid().ToString(),
                CreatedOn = DateTime.Now,
                CodEstado = 1
            

            };

            db.Cliente.Add(nuevoCliente);
            db.SaveChanges();
        }
        
        public List<ClienteEntity> ListarTodos()
        {
            return null;
        }

        public ClienteEntity SearhByDNI(long dni)
        {
            //VER Si se puede buscar por un campo que no sea PRIMARY KEY
            var query = db.Cliente.Find(dni);
            try
            {
                var nuevoCliente = new ClienteEntity()
                {
                    Nombre = query.Nombre,
                    Apellido = query.Apellido,
                    DNI = query.DNI,
                    Domicilio = query.Domicilio,
                    EstadoCivil = query.EstadoCivil,
                    FechaNacimiento = query.FechaNacimiento,
                    Ingreso = query.Ingreso,
                    Ocupacion = query.Ocupacion,
                    Sexo = query.Sexo

                };
                return nuevoCliente;

            }
            catch
            {
                return null;
            }
         
        }
    }
}
