
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Lppa.Data
{

using System;
    using System.Collections.Generic;
    
public partial class Usuario
{

    public int ID { get; set; }

    public string Nombre { get; set; }

    public string Apellido { get; set; }

    public string Email { get; set; }

    public string Contraseña { get; set; }

    public System.DateTime FechaAlta { get; set; }

    public System.DateTime FechaBaja { get; set; }

    public int CodEstado { get; set; }

    public string CreatedBy { get; set; }

    public System.DateTime CreatedOn { get; set; }

    public string ChangedBy { get; set; }

    public System.DateTime ChangedOn { get; set; }

}

}
