//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lppa.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Veraz
    {
        public int ID { get; set; }
        public long DNI { get; set; }
        public string Observacion { get; set; }
        public System.DateTime FechaIngreso { get; set; }
        public System.DateTime FechaEgreso { get; set; }
    }
}
